### ISSUE TITLE
MAC related issue unknown

### ISSUE THREAD

**Issue by JellyEvan** [JellyEvan/547final_jks#87]
SERVER ERROR MESSAGE:
```
API_OCT_processing.py:34: DeprecationWarning: save is deprecated. Use insert_one or replace_one instead
  raw_file.save(dict)
```
CLIENT ERROR MESSAGE
```
(myVenv) Evans-MacBook-Pro:547final_JKS Home$ python3 t_API.py
Traceback (most recent call last):
  File "t_API.py", line 45, in <module>
    sampleDict["ydim"])
  File "/Users/Home/Documents/Programming/repos/547final_jks/API_OCT_processing.py", line 86, in base642numpy
    npa = base64.decodebytes(b64)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py", line 546, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (229) cannot be 1 more than a multiple of 4
```

**Comment by wesleyk-duke** [comment]
Can you do ```print(raw_image)``` and ```print(type(raw_image))``` right before the ```processed_image``` variable and tell me what they output?
